# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fc0a5745d94ced83289d5f119df594f7337d3bdda26a3635773a03cbfd81c5833ef4b78b887f787d840e2f171f2717a4dad5f5372eceae24d519559a3c00cf9

test:
  secret_key_base: d737802dc3a977ffc369707fb4adac9dfc233edd372ac13872cfd0da044de80afea2993369f5ee717df226293fa82b56b7de8f5d8d947d3ca77f0468fd82b71c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
